<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Services\Navigation\" />
    <Folder Include="Utilities\" />
    <Folder Include="Services\Audio\" />
    <Folder Include="Services\Display\" />
    <Folder Include="Services\Media\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VRA.Common\VRA.Common.csproj" />
  </ItemGroup>

</Project>
